package ru.gelin.android.weather.openweathermap;

import static ru.gelin.android.weather.openweathermap.WeatherConditionTypePriority.*;

/**
 *  Enumeration of declared condition types.
 */
public enum WeatherConditionType {

    THUNDERSTORM_RAIN_LIGHT(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_RAIN(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_RAIN_HEAVY(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_LIGHT(THUNDERSTORM_PRIORITY),
    THUNDERSTORM(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_HEAVY(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_RAGGED(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_DRIZZLE_LIGHT(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_DRIZZLE(THUNDERSTORM_PRIORITY),
    THUNDERSTORM_DRIZZLE_HEAVY(THUNDERSTORM_PRIORITY),
    
    DRIZZLE_LIGHT(DRIZZLE_PRIORITY),
    DRIZZLE(DRIZZLE_PRIORITY),
    DRIZZLE_HEAVY(DRIZZLE_PRIORITY),
    DRIZZLE_RAIN_LIGHT(DRIZZLE_PRIORITY),
    DRIZZLE_RAIN(DRIZZLE_PRIORITY),
    DRIZZLE_RAIN_HEAVY(DRIZZLE_PRIORITY),
    DRIZZLE_SHOWER(DRIZZLE_PRIORITY),

    RAIN_LIGHT(RAIN_PRIORITY),
    RAIN(RAIN_PRIORITY),
    RAIN_HEAVY(RAIN_PRIORITY),
    RAIN_VERY_HEAVY(RAIN_PRIORITY),
    RAIN_EXTREME(RAIN_PRIORITY),
    RAIN_FREEZING(RAIN_PRIORITY),
    RAIN_SHOWER_LIGHT(RAIN_PRIORITY),
    RAIN_SHOWER(RAIN_PRIORITY),
    RAIN_SHOWER_HEAVY(RAIN_PRIORITY),

    SNOW_LIGHT(SNOW_PRIORITY),
    SNOW(SNOW_PRIORITY),
    SNOW_HEAVY(SNOW_PRIORITY),
    SLEET(SNOW_PRIORITY),
    SNOW_SHOWER(SNOW_PRIORITY), 
    
    MIST(ATMOSPHERE_PRIORITY),
    SMOKE(ATMOSPHERE_PRIORITY),
    HAZE(ATMOSPHERE_PRIORITY),
    SAND_WHIRLS(ATMOSPHERE_PRIORITY),
    FOG(ATMOSPHERE_PRIORITY),

    CLOUDS_CLEAR(CLOUDS_PRIORITY),
    CLOUDS_FEW(CLOUDS_PRIORITY),
    CLOUDS_SCATTERED(CLOUDS_PRIORITY),
    CLOUDS_BROKEN(CLOUDS_PRIORITY),
    CLOUDS_OVERCAST(CLOUDS_PRIORITY), 
    
    TORNADO(EXTREME_PRIORITY),
    TROPICAL_STORM(EXTREME_PRIORITY),
    HURRICANE(EXTREME_PRIORITY),
    COLD(EXTREME_PRIORITY),
    HOT(EXTREME_PRIORITY),
    WINDY(EXTREME_PRIORITY),
    HAIL(EXTREME_PRIORITY);


    private int priority = -1;

    private WeatherConditionType(int priority) {
        this.priority = priority;
    }

    public int getPriority() {
        return this.priority;
    }

}
